backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "article"
    label: "Artikel"
    folder: "src/pages/article"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-page"}
      - {label: "Sprache", name: "lang", widget: "hidden", default: "de"}
      - {label: "Artikel Nummer", name: "articleNr", widget: "string"}
      - {label: "Kategorie", name: "category", widget: "string"}
      - {label: "Tabelle", name: "table", widget: "number"}
      - {label: "Position", name: "order", widget: "number"}
      - {label: "Beschreibung", name: "description", widget: "string"}
      - {label: "Einheit", name: "unit", widget: "string"}
      - {label: "Preis", name: "price", widget: "string"}
              
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Hauptseite"
        name: "Index Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, required: false, name: heading, widget: string}
          - {label: Subheading, required: false, name: subheading, widget: string}
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - {label: Body, name: body, widget: markdown}
      - file: "src/pages/products/fatto.md"
        label: "Fatto a Mano"
        name: "Fatto a Mano"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "fatto-page"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, required: false, name: heading, widget: string}
          - {label: Subheading, required: false, name: subheading, widget: string}
          - {label: Intro, name: intro, widget: string}  
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - label: 'Tabelle'
            name: 'table'
            widget: 'object'
            fields:
              - {label: "Überschrift", name: "heading", required: false, widget: string}
              - label: "Produkte"
                name: "products"
                widget: list
                fields:
                  - {
                   label: "Artikel",
                   name: "article",
                   widget: "relation",
                   collection: "article",
                   searchFields: ["articleNr"],
                   displayFields: ["articleNr", "description"],
                   valueField: "articleNr", 
                  }
                  - {
                   label: "Artikel-Nr. anzeigen?",
                   name: "showArticleNr",
                   widget: "boolean",
                  }
      - file: "src/pages/places/index.md"
        label: "Standort Seite"
        name: "Places Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "places-page"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, required: false, name: heading, widget: string}
          - {label: Subheading, required: false, name: subheading, widget: string}
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - {label: Body, name: body, widget: markdown}

