backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "article"
    label: "Artikel"
    folder: "src/pages/article"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-page"}
      - {label: "Sprache", name: "lang", widget: "hidden", default: "de"}
      - {label: "Artikel Nummer", name: "articleNr", widget: "string"}
      - {label: "Kategorie", name: "category", widget: "string"}
      - {label: "Tabelle", name: "table", widget: "number"}
      - {label: "Position", name: "order", widget: "number"}
      - {label: "Beschreibung", name: "description", widget: "string"}
      - {label: "Einheit", name: "unit", widget: "string"}
      - {label: "Preis", name: "price", widget: "string"}
              
  - name: "pages"
    label: "Seiten"
    files:
      - file: "src/pages/index.md"
        label: "Hauptseite"
        name: "Index Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Path, name: path, widget: hidden, default: "/"}
          - {label: Image, name: image, widget: image}
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Titel, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - {label: Body, name: body, widget: markdown}
      - file: "src/pages/places/index.md"
        label: "Standorte"
        name: "Places Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "places-page"}
          - {label: Path, name: path, widget: hidden, default: "/standorte/"}
          - {label: Image, name: image, widget: image}
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Titel, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - {label: Body, name: body, widget: markdown}
          - label: 'Standorte'
            name: 'places'
            widget: list
            fields:
              - { label: "Name", name: name, widget: string }        
              - { label: "Adresse", name: address, widget: string }
              - label: "Öffnungszeiten unter der Woche" 
                name: week
                widget: object
                fields:
                  - label: "Tage"
                    name: days
                    hint: "Mo. - Fr."
                    widget: string
                  - label: "Stunden"
                    name: hours
                    hint: "08:00 - 12:30 Uhr"
                    widget: string
              - label: "Öffnungszeiten am Wochenende" 
                name: weekend
                widget: object
                fields:
                  - label: "Tage"
                    name: days
                    hint: "Sa."
                    widget: string
                  - label: "Stunden"
                    name: hours
                    hint: "08:00 - 12:30 Uhr"
                    widget: string
              - label: "Infos" 
                name: info 
                hint: "z.B. immer Montags geschlossen"
                required: false
                widget: string
      - file: "src/pages/pricelist/index.md"
        label: "Preisliste"
        name: "Preisliste"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pricelist-page"}
          - {label: Path, name: path, widget: hidden, default: "/preisliste/"}
          - {label: Image, name: image, widget: image}
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Titel, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - {label: Preisliste, name: pricelist_pdf, widget: file}  
          - {label: Body, name: body, widget: markdown}
      - file: "src/pages/terms/index.md"
        label: "Konditionen"
        name: "Konditionen"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-page"}
          - {label: Path, name: path, widget: hidden, default: "/konditionen/"}
          - {label: Image, name: image, widget: image}
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Titel, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - {label: Body, name: body, widget: markdown}
      - file: "src/pages/contact/index.md"
        label: "Kontakt"
        name: "Kontakt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: Path, name: path, widget: hidden, default: "/kontakt/"}
          - {label: Image, name: image, widget: image}
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Titel, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - {label: Body, name: body, widget: markdown}
      - file: "src/pages/dataprotection/index.md"
        label: "Datenschutz"
        name: "Datenschutz"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-page"}
          - {label: Path, name: path, widget: hidden, default: "/datenschutz/"}
          - {label: Image, required: false, name: image, widget: image}
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Titel, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - {label: Body, name: body, widget: markdown}
      - file: "src/pages/imprint/index.md"
        label: "Impressum"
        name: "Impressum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-page"}
          - {label: Path, name: path, widget: hidden, default: "/impressum/"}
          - {label: Image, required: false, name: image, widget: image}
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Titel, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - {label: Body, name: body, widget: markdown}

  - name: "product_pages"
    label: "Produkt-Seiten"
    files:
      - file: "src/pages/products/index.md"
        label: "Hauptseite"
        name: "Hauptseite"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Path, name: path, widget: hidden, default: "/produkte/"}
          - {label: Image, name: image, widget: image}
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Titel, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - {label: Body, name: body, widget: markdown}
      - file: "src/pages/products/fatto.md"
        label: "Fatto a Mano"
        name: "Fatto a Mano"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "fatto-page"}
          - {label: Path, name: path, widget: hidden, default: "/produkte/fatto_a_mano/"}
          - {label: Image, name: image, widget: image}
          - {label: Meta, name: meta, widget: object, fields: [
            {label: Titel, name: title, widget: string},
            {label: Beschreibung, name: description, widget: text},
            {label: Keywords, name: keywords, widget: string}
          ]}  
          - {label: Body, name: body, widget: markdown}
          - label: 'Produkt Tabelle'
            name: 'fatto_table'
            widget: 'object'
            fields:
              - {label: "Überschrift", name: "heading", required: false, widget: string}
              - {label: "Spaltennamen Anzeigen?", name: "showColName", widget: boolean}
              - label: "Produkte"
                name: "products"
                widget: list
                fields:
                  - {
                   label: "Artikel",
                   name: "article",
                   widget: "relation",
                   collection: "article",
                   searchFields: ["articleNr"],
                   displayFields: ["articleNr", "description"],
                   valueField: "articleNr", 
                  }
                  - {
                   label: "Artikel-Nr. anzeigen?",
                   name: "showArticleNr",
                   widget: "boolean",
                  }
